var num1=20,num2=400,num3=50;
if((num1>num2)&&(num1>num3)){
    if(num2>num3){
        console.log(num2);
    }
    else{
        console.log(num3);
    }
}
if((num2>num1)&&(num2>num3)){
    if(num1>num3){
        console.log(num1);
    }
    else{
        console.log(num3);
    }
}
if((num3>num1)&&(num3>num2)){
    if(num1>num2){
        console.log(num1);
    }
    else{
        console.log(num2);
    }
}